version: "3.9"

services:
  server:
    build: ./Server
    container_name: cloneai-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./Server/.env
    environment:
      NODE_ENV: production

  client:
    build: ./Client
    container_name: cloneai-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
