version: "3.9"

services:
  backend:
    build: ./Server
    container_name: cloneai-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./Server/.env
    environment:
      NODE_ENV: production

  frontend:
    build: ./Client
    container_name: cloneai-frontend
    restart: always
    ports:
      - "80:80"
